# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0015_auto_20170321_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
