# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_dictionary', '0016_auto_20170502_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='english',
            new_name='english_word',
        ),
    ]
